version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1000 # we don't want to limit PRs
    schedule:
      interval: "daily" # runs on every weekday, Monday to Friday
    ignore:
      # We can't update these dependencies without doing a lot of work:
      - dependency-name: "jquery*"
